// <auto-generated />
using System;
using API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(HighScoreDbContext))]
    partial class HighScoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Entities.Highscore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Time")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Highscores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0788d2f-8003-43c1-92a4-edc76a7c5dde"),
                            Name = "Hattori Hanzo",
                            Time = 150L
                        },
                        new
                        {
                            Id = new Guid("6313179f-7837-473a-a4d5-a5571b43e6a6"),
                            Name = "Vincent Vega",
                            Time = 160L
                        },
                        new
                        {
                            Id = new Guid("bf3f3002-7e53-441e-8b76-f6280be284aa"),
                            Name = "Beatrix Kiddo",
                            Time = 170L
                        },
                        new
                        {
                            Id = new Guid("fe98f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Name = "Calvin Candie",
                            Time = 180L
                        },
                        new
                        {
                            Id = new Guid("1098f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Name = "Bill",
                            Time = 190L
                        },
                        new
                        {
                            Id = new Guid("1198f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Name = "Winston Wolf",
                            Time = 200L
                        },
                        new
                        {
                            Id = new Guid("1298f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Name = "Jackie Brown",
                            Time = 210L
                        },
                        new
                        {
                            Id = new Guid("1398f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Name = "Marsellus Wallace",
                            Time = 220L
                        },
                        new
                        {
                            Id = new Guid("1498f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Name = "Mr Pink",
                            Time = 230L
                        },
                        new
                        {
                            Id = new Guid("1598f549-e790-4e9f-aa16-18c2292a2ee9"),
                            Name = "Zed",
                            Time = 240L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
